In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('master.csv')

In [3]:
data.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

In [4]:
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
data.columns

Index(['country', 'year', 'sex', 'age', 'suicides_no', 'population',
       'suicides/100k pop', 'country-year', 'HDI for year',
       ' gdp_for_year ($) ', 'gdp_per_capita ($)', 'generation'],
      dtype='object')

In [6]:
country = pd.DataFrame(data.groupby('country')['suicides/100k pop'].mean()).reset_index()

In [7]:
country

                          country  suicides/100k pop
0                         Albania           3.502879
1             Antigua and Barbuda           0.552901
2                       Argentina          10.469328
3                         Armenia           3.275872
4                           Aruba           9.503095
5                       Australia          12.992806
6                         Austria          23.759764
7                      Azerbaijan           1.855417
8                         Bahamas           1.247391
9                         Bahrain           1.854127
10                       Barbados           2.970433
11                        Belarus          31.075913
12                        Belgium          21.237903
13                         Belize           6.230625
14         Bosnia and Herzegovina           4.617083
15                         Brazil           5.846022
16                       Bulgaria          19.489111
17                     Cabo Verde          11.153333
18                         Canada          12.467586
19                          Chile          10.542043
20                       Colombia           5.401586
21                     Costa Rica           7.093667
22                        Croatia          22.835267
23                           Cuba          21.222049
24                         Cyprus           3.293596
25                 Czech Republic          18.487547
26                        Denmark          14.097159
27                       Dominica           0.000000
28                        Ecuador           6.304328
29                    El Salvador          10.541458
..                            ...                ...
71                    Puerto Rico          10.186237
72                          Qatar           1.787360
73              Republic of Korea          25.135618
74                        Romania          12.489671
75             Russian Federation          34.892377
76          Saint Kitts and Nevis           0.000000
77                    Saint Lucia           7.202738
78   Saint Vincent and Grenadines           5.755433
79                     San Marino           4.045000
80                         Serbia          22.164120
81                     Seychelles           7.480093
82                      Singapore          17.045645
83                       Slovakia          12.568788
84                       Slovenia          27.827857
85                   South Africa           0.964542
86                          Spain           9.432957
87                      Sri Lanka          35.295152
88                       Suriname          21.316429
89                         Sweden          14.658436
90                    Switzerland          19.024087
91                       Thailand           7.073862
92            Trinidad and Tobago          13.825648
93                         Turkey           2.371071
94                   Turkmenistan           8.605546
95                        Ukraine          26.582321
96           United Arab Emirates           1.317917
97                 United Kingdom           7.502473
98                  United States          13.819812
99                        Uruguay          19.461190
100                    Uzbekistan           8.099129

[101 rows x 2 columns]

In [8]:
import numpy as np
import pandas as pd
import shapefile as shp
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from pycountry_convert import country_alpha2_to_continent_code, country_name_to_country_alpha2

In [9]:
def get_continent(col):
    try:
        cn_a2_code =  country_name_to_country_alpha2(col)
    except:
        cn_a2_code = 'Unknown' 
    return cn_a2_code

In [10]:
country['code'] = country.country.apply(get_continent)

In [11]:
from geopy.geocoders import Nominatim
geolocator = Nominatim()
def geolocate(country):
    try:
        # Geolocate the center of the country
        loc = geolocator.geocode(country)
        # And return latitude and longitude
        return (loc.latitude, loc.longitude)
    except:
        # Return missing value
        return (-1, -1)

C:\Users\xinrui zhan\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: Using Nominatim with the default "geopy/1.22.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.

In [ ]:
geo = country.country.apply(geolocate).to_list()

In [ ]:
country['lon'] = [x[1] for x in geo]
country['lat'] = [x[0] for x in geo]

In [ ]:
import folium
from folium.plugins import MarkerCluster
world_map= folium.Map(tiles="cartodbpositron")
marker_cluster = MarkerCluster().add_to(world_map)

In [ ]:
df = country
convert_ISO_3166_2_to_1 = {
'AF':'AFG',
'AX':'ALA',
'AL':'ALB',
'DZ':'DZA',
'AS':'ASM',
'AD':'AND',
'AO':'AGO',
'AI':'AIA',
'AQ':'ATA',
'AG':'ATG',
'AR':'ARG',
'AM':'ARM',
'AW':'ABW',
'AU':'AUS',
'AT':'AUT',
'AZ':'AZE',
'BS':'BHS',
'BH':'BHR',
'BD':'BGD',
'BB':'BRB',
'BY':'BLR',
'BE':'BEL',
'BZ':'BLZ',
'BJ':'BEN',
'BM':'BMU',
'BT':'BTN',
'BO':'BOL',
'BA':'BIH',
'BW':'BWA',
'BV':'BVT',
'BR':'BRA',
'IO':'IOT',
'BN':'BRN',
'BG':'BGR',
'BF':'BFA',
'BI':'BDI',
'KH':'KHM',
'CM':'CMR',
'CA':'CAN',
'CV':'CPV',
'KY':'CYM',
'CF':'CAF',
'TD':'TCD',
'CL':'CHL',
'CN':'CHN',
'CX':'CXR',
'CC':'CCK',
'CO':'COL',
'KM':'COM',
'CG':'COG',
'CD':'COD',
'CK':'COK',
'CR':'CRI',
'CI':'CIV',
'HR':'HRV',
'CU':'CUB',
'CY':'CYP',
'CZ':'CZE',
'DK':'DNK',
'DJ':'DJI',
'DM':'DMA',
'DO':'DOM',
'EC':'ECU',
'EG':'EGY',
'SV':'SLV',
'GQ':'GNQ',
'ER':'ERI',
'EE':'EST',
'ET':'ETH',
'FK':'FLK',
'FO':'FRO',
'FJ':'FJI',
'FI':'FIN',
'FR':'FRA',
'GF':'GUF',
'PF':'PYF',
'TF':'ATF',
'GA':'GAB',
'GM':'GMB',
'GE':'GEO',
'DE':'DEU',
'GH':'GHA',
'GI':'GIB',
'GR':'GRC',
'GL':'GRL',
'GD':'GRD',
'GP':'GLP',
'GU':'GUM',
'GT':'GTM',
'GG':'GGY',
'GN':'GIN',
'GW':'GNB',
'GY':'GUY',
'HT':'HTI',
'HM':'HMD',
'VA':'VAT',
'HN':'HND',
'HK':'HKG',
'HU':'HUN',
'IS':'ISL',
'IN':'IND',
'ID':'IDN',
'IR':'IRN',
'IQ':'IRQ',
'IE':'IRL',
'IM':'IMN',
'IL':'ISR',
'IT':'ITA',
'JM':'JAM',
'JP':'JPN',
'JE':'JEY',
'JO':'JOR',
'KZ':'KAZ',
'KE':'KEN',
'KI':'KIR',
'KP':'PRK',
'KR':'KOR',
'KW':'KWT',
'KG':'KGZ',
'LA':'LAO',
'LV':'LVA',
'LB':'LBN',
'LS':'LSO',
'LR':'LBR',
'LY':'LBY',
'LI':'LIE',
'LT':'LTU',
'LU':'LUX',
'MO':'MAC',
'MK':'MKD',
'MG':'MDG',
'MW':'MWI',
'MY':'MYS',
'MV':'MDV',
'ML':'MLI',
'MT':'MLT',
'MH':'MHL',
'MQ':'MTQ',
'MR':'MRT',
'MU':'MUS',
'YT':'MYT',
'MX':'MEX',
'FM':'FSM',
'MD':'MDA',
'MC':'MCO',
'MN':'MNG',
'ME':'MNE',
'MS':'MSR',
'MA':'MAR',
'MZ':'MOZ',
'MM':'MMR',
'NA':'NAM',
'NR':'NRU',
'NP':'NPL',
'NL':'NLD',
'AN':'ANT',
'NC':'NCL',
'NZ':'NZL',
'NI':'NIC',
'NE':'NER',
'NG':'NGA',
'NU':'NIU',
'NF':'NFK',
'MP':'MNP',
'NO':'NOR',
'OM':'OMN',
'PK':'PAK',
'PW':'PLW',
'PS':'PSE',
'PA':'PAN',
'PG':'PNG',
'PY':'PRY',
'PE':'PER',
'PH':'PHL',
'PN':'PCN',
'PL':'POL',
'PT':'PRT',
'PR':'PRI',
'QA':'QAT',
'RE':'REU',
'RO':'ROU',
'RU':'RUS',
'RW':'RWA',
'BL':'BLM',
'SH':'SHN',
'KN':'KNA',
'LC':'LCA',
'MF':'MAF',
'PM':'SPM',
'VC':'VCT',
'WS':'WSM',
'SM':'SMR',
'ST':'STP',
'SA':'SAU',
'SN':'SEN',
'RS':'SRB',
'SC':'SYC',
'SL':'SLE',
'SG':'SGP',
'SK':'SVK',
'SI':'SVN',
'SB':'SLB',
'SO':'SOM',
'ZA':'ZAF',
'GS':'SGS',
'ES':'ESP',
'LK':'LKA',
'SD':'SDN',
'SR':'SUR',
'SJ':'SJM',
'SZ':'SWZ',
'SE':'SWE',
'CH':'CHE',
'SY':'SYR',
'TW':'TWN',
'TJ':'TJK',
'TZ':'TZA',
'TH':'THA',
'TL':'TLS',
'TG':'TGO',
'TK':'TKL',
'TO':'TON',
'TT':'TTO',
'TN':'TUN',
'TR':'TUR',
'TM':'TKM',
'TC':'TCA',
'TV':'TUV',
'UG':'UGA',
'UA':'UKR',
'AE':'ARE',
'GB':'GBR',
'US':'USA',
'UM':'UMI',
'UY':'URY',
'UZ':'UZB',
'VU':'VUT',
'VE':'VEN',
'VN':'VNM',
'VG':'VGB',
'VI':'VIR',
'WF':'WLF',
'EH':'ESH',
'YE':'YEM',
'ZM':'ZMB',
'ZW':'ZWE'
}
country['id'] = country.code.apply(lambda x: convert_ISO_3166_2_to_1[x] if x in convert_ISO_3166_2_to_1.keys() else 'unkown')

In [ ]:
#empty map
world_map= folium.Map()
marker_cluster = MarkerCluster().add_to(world_map)
#for each coordinate, create circlemarker of user percent
for i in range(len(df)):
        lat = df.iloc[i]['lat']
        long = df.iloc[i]['lon']
        radius=5
        popup_text = """Country : {}<br>
                    # of Suicides: {}<br>"""
        popup_text = popup_text.format(df.iloc[i]['country'],
                                   df.iloc[i]['suicides_no']
                                   )
        folium.CircleMarker(location = [lat, long], radius=radius, popup= popup_text, fill =True).add_to(marker_cluster)
#show the map
world_map.save(outfile= "test.html")

In [ ]:
world_map

In [ ]:
m = folium.Map(tiles="cartodbpositron")

In [89]:
df

,country,suicides_no,code,lon,lat,id
0,Albania,1970,AL,19.999962,41.000028,ALB
1,Antigua and Barbuda,11,AG,-61.955461,17.223472,ATG
2,Argentina,82219,AR,-64.967282,-34.996496,ARG
3,Armenia,1905,AM,44.673665,40.769627,ARM
4,Aruba,101,AW,-69.961848,12.501363,ABW
5,Australia,70111,AU,134.755000,-24.776109,AUS
6,Austria,50073,AT,13.199959,47.200034,AUT
7,Azerbaijan,1656,AZ,47.787251,40.393629,AZE
8,Bahamas,93,BS,-78.000055,24.773655,BHS
9,Bahrain,463,BH,50.534461,26.155125,BHR
10,Barbados,177,BB,-59.525030,13.150033,BRB
11,Belarus,59892,BY,27.697136,53.425061,BLR
12,Belgium,62761,BE,4.666715,50.640281,BEL
13,Belize,348,BZ,-88.760093,16.825979,BLZ
14,Bosnia and Herzegovina,318,BA,17.596147,44.305348,BIH
15,Brazil,226613,BR,-53.200000,-10.333333,BRA
16,Bulgaria,36388,BG,25.485662,42.607397,BGR
17,Cabo Verde,42,CV,-24.008395,16.000055,CPV
18,Canada,107561,CA,-107.991707,61.066692,CAN
19,Chile,40895,CL,-71.318770,-31.761336,CHL
20,Colombia,53080,CO,-73.783892,2.889443,COL
21,Costa Rica,6792,CR,-84.073910,10.273563,CRI
22,Croatia,18429,HR,17.011895,45.564344,HRV
23,Cuba,41418,CU,-80.832875,23.013134,CUB
24,Cyprus,412,CY,33.145128,34.982302,CYP
25,Czech Republic,43687,CZ,15.474954,49.816700,CZE
26,Denmark,15297,DK,10.333328,55.670249,DNK
27,Dominica,0,DM,-70.302803,19.097403,DMA
28,Ecuador,20660,EC,-79.366697,-1.339767,ECU
29,El Salvador,11683,SV,-88.914068,13.800038,SLV
...,...,...,...,...,...,...
71,Puerto Rico,9043,PR,-66.413282,18.221415,PRI
72,Qatar,574,QA,51.229529,25.333698,QAT
73,Republic of Korea,261730,Unknown,127.696119,36.638392,unkown
74,Romania,72777,RO,24.685923,45.985213,ROU
75,Russian Federation,1209742,RU,97.745306,64.686314,RUS
76,Saint Kitts and Nevis,0,KN,-62.672597,17.250512,KNA
77,Saint Lucia,230,LC,-60.975036,13.825049,LCA
78,Saint Vincent and Grenadines,124,Unknown,-61.276557,12.904470,unkown
79,San Marino,4,SM,12.458306,43.945862,SMR
80,Serbia,24179,RS,21.076574,44.024323,SRB
81,Seychelles,98,SC,55.454015,-4.657498,SYC
82,Singapore,10089,SG,103.819499,1.357107,SGP
83,Slovakia,13437,SK,19.452865,48.741152,SVK
84,Slovenia,10615,SI,14.480837,45.813311,SVN
85,South Africa,7321,ZA,24.991639,-28.816624,ZAF
86,Spain,100202,ES,-4.838065,39.326234,ESP
87,Sri Lanka,55641,LK,80.713785,7.555494,LKA
88,Suriname,2166,SR,-56.077119,4.141303,SUR
89,Sweden,37795,SE,14.520858,59.674971,SWE
90,Switzerland,26217,CH,8.231974,46.798562,CHE
91,Thailand,110643,TH,100.832730,14.897192,THA
92,Trinidad and Tobago,4039,TT,-60.982107,10.867785,TTO
93,Turkey,10131,TR,34.924965,38.959759,TUR
94,Turkmenistan,8624,TM,59.392461,39.376381,TKM
95,Ukraine,319950,UA,31.271832,49.487197,UKR
96,United Arab Emirates,622,AE,53.999483,24.000249,ARE
97,United Kingdom,136805,GB,-3.276575,54.702354,GBR
98,United States,1034013,US,-100.445882,39.783730,USA
99,Uruguay,13138,UY,-56.020153,-32.875555,URY
100,Uzbekistan,34803,UZ,63.952810,41.323730,UZB

In [78]:
import requests
country_shapes = 'https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/world-countries.json'

In [91]:
folium.Choropleth(
    #The GeoJSON data to represent the world country
    geo_data= country_shapes,
    name='Countries Total # of Suicides',
    data=df,
    #The column aceppting list with 2 value; The country name and  the numerical value
    columns=['id', 'suicides_no'],
    key_on='feature.id',
    fill_color='Blues',
    nan_fill_color='black',
    fill_opacity = 0.8
).add_to(m)

In [92]:
marker_cluster = MarkerCluster().add_to(m)
#for each coordinate, create circlemarker of user percent
for i in range(len(df)):
        lat = df.iloc[i]['lat']
        long = df.iloc[i]['lon']
        radius=5
        popup_text = """Country : {}<br>
                    # of Suicides: {}<br>"""
        popup_text = popup_text.format(df.iloc[i]['country'],
                                   df.iloc[i]['suicides_no']
                                   )
        folium.CircleMarker(location = [lat, long], radius=radius, popup= popup_text, fill =True).add_to(marker_cluster)

In [94]:
m.save(outfile= "final.html")

In [ ]:
# generation